### ISSUE TITLE
How to install with docker-compose

### ISSUE THREAD

**Issue by noavolution** [jmlemetayer/abba#25]
I am trying to install abba wit docker compose. This is what my file looks like:
```
version: '3'

services:
  cdn:
    image: jmlemetayer/abba:latest
    container_name: cdn
    restart: unless-stopped
    volumes:
      - /var/lib/docker/cdn:/var/www
    networks:
      - cdn
      - traefik-proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.cdn.entrypoints=http"
      - "traefik.http.routers.cdn.rule=Host(`cdn.n-j.me`)"
      - "traefik.http.middlewares.cdn-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.cdn.middlewares=cdn-https-redirect"
      - "traefik.http.routers.cdn-secure.entrypoints=https"
      - "traefik.http.routers.cdn-secure.rule=Host(`cdn.n-j.me`)"
      - "traefik.http.routers.cdn-secure.tls=true"
      - "traefik.http.routers.cdn-secure.tls.certresolver=http"
      - "traefik.http.routers.cdn-secure.service=cdn"
      - "traefik.http.services.cdn.loadbalancer.server.port=80"
      - "traefik.docker.network=traefik-proxy"

networks:
  traefik-proxy:
    external: true
  cdn:
```
When I start the container I get the error "failed to install abba". What am I doing wrong?
